### ISSUE TITLE
object __array__ method not producing an array error on Google Colab

### ISSUE THREAD

**Issue by petulla** [explosion/spacy-pytorch-transformers#21]
## How to reproduce the behaviour

This is on Google Colab with Python 3.6 and GPU enabled runtime. Seems similar to [this error](https://github.com/explosion/spaCy/issues/2161) but is throwing on nlp.update().

First install GPU spacy and spacy-pytorch-transformers.

```
!pip install -U spacy[cuda100]
!pip install spacy-pytorch-transformers
!python -m spacy download en_pytt_bertbaseuncased_lg
```

Import defaults after restarting runtime

```
import spacy
from spacy.util import minibatch
import random
import torch
import re
import copy
```

Use default setup from introduction docs.

```
TRAIN_DATA = [
    ("text1", {"cats": {"POSITIVE": 1.0, "NEGATIVE": 0.0}})
]

is_using_gpu = spacy.prefer_gpu()
if is_using_gpu:
    torch.set_default_tensor_type("torch.cuda.FloatTensor")

nlp = spacy.load("en_pytt_bertbaseuncased_lg")

    
print(nlp.pipe_names) # ["sentencizer", "pytt_wordpiecer", "pytt_tok2vec"]
textcat = nlp.create_pipe("pytt_textcat", config={"exclusive_classes": True})
for label in ("POSITIVE", "NEGATIVE"):
    textcat.add_label(label)
nlp.add_pipe(textcat)

optimizer = nlp.resume_training()
for i in range(10):
    random.shuffle(TRAIN_DATA)
    losses = {}
    for batch in minibatch(TRAIN_DATA, size=8):
        texts, cats = zip(*batch)
        nlp.update(texts, cats, sgd=optimizer, losses=losses)
    print(i, losses)
```

Throwing a type error:
```
/usr/local/lib/python3.6/dist-packages/numpy/lib/arraypad.py in pad(array, pad_width, mode, **kwargs)
   1169         raise TypeError('`pad_width` must be of integral type.')
   1170 
-> 1171     narray = np.array(array)
   1172     pad_width = _as_pairs(pad_width, narray.ndim, as_index=True)
   1173 

ValueError: object __array__ method not producing an array
```

## Your Environment
Google Colab

* **spaCy version:** 2.1.7
* **Platform:** Linux-4.14.79+-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.8

**Comment by tsoernes** [comment]
I've got the same, but with python 3.7. numpy 1.16.4

**Comment by einarbmag** [comment]
I'm having related issues. I get the same error if I use gpu (with spacy[cuda90]). If I use cpu, I get :
IndexError: index 1 is put of bounds for axis 0 with size 1
(line 86 in spacy_pytorch_transformers/util.py)

This is happening at model training, nlp.update

**Comment by tsoernes** [comment]
I get the very same error when running locally; no IPython/Jupyter/Colab.
```
thinc                      7.0.8       
thinc-gpu-ops              0.0.4       
torch                      1.1.0
spacy [cuda100]                      2.1.7       
spacy-pytorch-transformers 0.0.1
numpy                      1.16.4      
nvidia-ml-py3              7.352.0 
ideep4py                   2.0.0.post3 
en-pytt-bertbaseuncased-lg 2.1.0       
cupy-cuda100               7.0.0b2        
```

**Comment by igormis** [comment]
Just place
`!pip install -U spacy[cuda92]`

**Comment by igormis** [comment]
I aslo have the same issue, tried with numpy==1.17.0, but no luck

**Comment by petulla** [comment]
This appears to work with `!pip install -U spacy[cuda92]`. Others should try to confirm.

**Comment by igormis** [comment]
> This appears to work with `!pip install -U spacy[cuda92]`. Others should try to confirm.
No it did not worked it raised some other issues.

**Comment by honnibal** [comment]
Can you check whether `spacy.prefer_gpu()` prints `True`, and whether `import cupy; arr = cupy.zeros((1,1))` works correctly? If you can use cupy you should be able to use the GPU capabilities.

**Comment by petulla** [comment]
![Screen Shot 2019-08-09 at 3 19 54 PM](https://user-images.githubusercontent.com/3466817/62803723-2e4c9e00-bab9-11e9-832b-57c3802515d9.png)

**Comment by igormis** [comment]
The same here:
True
[[0.]]
But still throws the same exception. Here is the link from the notebook (https://bit.ly/2GYuNJP).
The Pytorch version is 1.1.0, Cuda is 10.0.
I tried also pip install -U chainer, but it did not help...

**Comment by igormis** [comment]
In addition, one hint for the solution is to is to convert cupy to numpy. 
You can use chainer's to_cpu method to convert from GPU to CPU.
import chainer.cuda
ndarray_cpu = chainer.cuda.to_cpu (ndarray_gpu)

The problem is where to use this? in util.py?

**Comment by honnibal** [comment]
You shouldn't have to convert stuff to CPU. I'm not sure what the problem is, but it does seem like the GPU isn't being set up correctly on Colab. This is surprising because I think other uses had it working successfully.

What's the result of:

```import thinc_gpu_ops
print(dir(thinc_gpu_ops))
```

**Comment by igormis** [comment]
['AVAILABLE', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'about', 'backprop_max_pool', 'backprop_mean_pool', 'backprop_sum_pool', 'gpu_ops', 'hash', 'max_pool', 'maxout', 'mean_pool', 'np', 'sum_pool']

**Comment by honnibal** [comment]
That's correct too. I don't understand what's wrong here. Could you provide the full traceback? I only got a couple of lines above.

**Comment by igormis** [comment]
The good news is that now everythng works on colab, I just installed torch=1.0.0 and then remove it and install torch=1.1.0 , very strange.

Here is the colab code.
https://colab.research.google.com/drive/1oUMvOqlm4Cjr34jJnlXv_mrxewuKHS7X

**Comment by honnibal** [comment]
See #21

**Comment by petulla** [comment]
This is working. My installs before any imports:

```
!pip install torch==1.1.0 -U
!pip install pytorch_pretrained_bert
!pip install -U spacy[cuda100]
!pip install spacy-pytorch-transformers[cuda100]==0.1.1
!python -m spacy download en_pytt_bertbaseuncased_lg
```

The runtime has to be restarted at least once after install.
