### ISSUE TITLE
AttributeError: type object 'BertModel' has no attribute 'config'

### ISSUE THREAD

**Issue by jameszlj** [explosion/spacy-pytorch-transformers#22]
In [1]: import spacy
   ...:
   ...: nlp = spacy.load("en_pytt_bertbaseuncased_lg")
   ...:
   ...:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-f6a64ff85561> in <module>()
      1 import spacy
      2
----> 3 nlp = spacy.load("en_pytt_bertbaseuncased_lg")

c:\users\win10\envs\ml_py3\lib\site-packages\spacy\__init__.py in load(name, **overrides)
     25     if depr_path not in (True, False, None):
     26         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 27     return util.load_model(name, **overrides)
     28
     29

c:\users\win10\envs\ml_py3\lib\site-packages\spacy\util.py in load_model(name, **overrides)
    134             return load_model_from_package(name, **overrides)
    135         if Path(name).exists():  # path to model data directory
--> 136             return load_model_from_path(Path(name), **overrides)
    137     elif hasattr(name, "exists"):  # Path or Path-like to model data
    138         return load_model_from_path(name, **overrides)

c:\users\win10\envs\ml_py3\lib\site-packages\spacy\util.py in load_model_from_path(model_path, meta, **overrides)
    177             component = nlp.create_pipe(name, config=config)
    178             nlp.add_pipe(component, name=name)
--> 179     return nlp.from_disk(model_path)
    180
    181

c:\users\win10\envs\ml_py3\lib\site-packages\spacy\language.py in from_disk(self, path, exclude, disable)
    830             # Convert to list here in case exclude is (default) tuple
    831             exclude = list(exclude) + ["vocab"]
--> 832         util.from_disk(path, deserializers, exclude)
    833         self._path = path
    834         return self

c:\users\win10\envs\ml_py3\lib\site-packages\spacy\util.py in from_disk(path, readers, exclude)
    634         # Split to support file names like meta.json
    635         if key.split(".")[0] not in exclude:
--> 636             reader(path / key)
    637     return path
    638

c:\users\win10\envs\ml_py3\lib\site-packages\spacy\language.py in <lambda>(p, proc)
    825                 continue
    826             deserializers[name] = lambda p, proc=proc: proc.from_disk(
--> 827                 p, exclude=["vocab"]
    828             )
    829         if not (path / "vocab").exists() and "vocab" not in exclude:

pipes.pyx in spacy.pipeline.pipes.Pipe.from_disk()

c:\users\win10\envs\ml_py3\lib\site-packages\spacy\util.py in from_disk(path, readers, exclude)
    634         # Split to support file names like meta.json
    635         if key.split(".")[0] not in exclude:
--> 636             reader(path / key)
    637     return path
    638

pipes.pyx in spacy.pipeline.pipes.Pipe.from_disk.load_model()

c:\users\win10\envs\ml_py3\lib\site-packages\spacy_pytorch_transformers\tok2vec.py in Model(cls, **cfg)
     61         else:
     62             pytt_model = PyTT_Wrapper(name)
---> 63         nO = pytt_model.nO
     64         batch_by_length = cfg.get("words_per_batch", 3000)
     65         max_length = cfg.get("max_length", 512)

c:\users\win10\envs\ml_py3\lib\site-packages\spacy_pytorch_transformers\wrapper.py in nO(self)
     35     @property
     36     def nO(self):
---> 37         return self._model.config.hidden_size
     38
     39     @property

AttributeError: type object 'BertModel' has no attribute 'config'

Is there a solution?
python 3.6
'en_pytt_bertbaseuncased_lg 2.1.1
spacy-pytorch-transformers==0.0.1
spacy 2.1.7

**Comment by ines** [comment]
This should be fixed in #19 (also see #15). We're just getting the next release ready.
