### ISSUE TITLE
 AttributeError: module 'thinc_gpu_ops' has no attribute 'mean_pool'

### ISSUE THREAD

**Issue by igormis** [explosion/spacy-pytorch-transformers#27]
I installed the 
`pip3 install spacy-pytorch-transformers[cuda100]`
and 
`python3 -m spacy download en_pytt_xlnetbasecased_lg`
but when I run the example: 
`python3 train_textcat.py en_pytt_xlnetbasecased_lg -o ./results -n 10`
I get the following error:
`AttributeError: module 'thinc_gpu_ops' has no attribute 'mean_pool`

Here is my env:
`blis (0.2.4)
boto3 (1.9.205)
botocore (1.12.205)
certifi (2019.6.16)
chardet (3.0.4)
cupy-cuda100 (7.0.0b2)
cymem (2.0.2)
dataclasses (0.6)
docutils (0.14)
en-pytt-xlnetbasecased-lg (2.1.1)
fastrlock (0.4)
ftfy (5.6)
idna (2.8)
jmespath (0.9.4)
murmurhash (1.0.2)
numpy (1.17.0)
pip (9.0.1)
pkg-resources (0.0.0)
plac (0.9.6)
preshed (2.0.1)
python-dateutil (2.8.0)
pytorch-transformers (1.0.0)
regex (2019.6.8)
requests (2.22.0)
s3transfer (0.2.1)
sentencepiece (0.1.82)
setuptools (39.0.1)
six (1.12.0)
spacy (2.1.8)
spacy-pytorch-transformers (0.1.0)
srsly (0.0.7)
thinc (7.0.8)
thinc-gpu-ops (0.0.4)
torch (1.2.0)
torchcontrib (0.0.2)
tqdm (4.33.0)
urllib3 (1.25.3)
wasabi (0.2.2)
wcwidth (0.1.7)
`
and nvcc --version give this output:
`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
`
When I exectute the code on CPU everything seems ok...

**Comment by honnibal** [comment]
This means that the `thinc-gpu-ops` library didn't compile correctly. What OS are you on? If on Linux, you'll need `build-essential` and `python3-dev` installed.

**Comment by igormis** [comment]
OS:
Ubuntu 18.04 LTS
Cuda 10.0 & cuddn 7.5.0
Python 3.6.7

**Comment by igormis** [comment]
When I tried on colab everything is ok, but when i try to train using`train_textcat.py ` I get the following error:

**Comment by honnibal** [comment]
See #21

**Comment by mkaze** [comment]
@honnibal I also experience the same problem on my local machine and the solutions offered in #21 did not help me. I have used `pip install spacy-pytorch-transformers[cuda100]`. All the packages were installed successfully, but I get this error when I start training of the model i.e. `nlp.update(...)`:

```
~/py3envs/spacy_trans_env/lib/python3.6/site-packages/thinc/neural/pooling.py in mean_pool(X_lengths, drop)
     51     else:
     52         ops = CupyOps()
---> 53     output = ops.mean_pool(X, lengths)
     54 
     55     def finish_update(d_output, sgd=None):

ops.pyx in thinc.neural.ops.CupyOps.mean_pool()

AttributeError: module 'thinc_gpu_ops' has no attribute 'mean_pool'
```

OS spec:
Ubuntu 16.04 LTS
CUDA 10.0
CuDNN 7.6.2
Python 3.6.9

Here is the list of relevant installed packages:
```
cupy-cuda100==7.0.0b2
de-pytt-bertbasecased-lg==2.1.1
numpy==1.17.0
pytorch-transformers==1.0.0
spacy==2.1.8
spacy-pytorch-transformers==0.2.0
thinc==7.0.8
thinc-gpu-ops==0.0.4
torch==1.2.0
torchcontrib==0.0.2
```
Further, the output of `spacy.prefer_gpu()` is `True` and `import cupy; arr = cupy.zeros((1,1))` works correctly. I have also tried to reinstall all the packages, but it also did not work. Maybe `thinc-gpu-ops` does not fully support CUDA 10.0?! I am not sure!

**Comment by davidlenz** [comment]
Facing the same issue as @mkaze on Win 10, CUDA 9.0

**Comment by mkaze** [comment]
@honnibal I think it's very likely that there is a problem with `thinc_gpu_ops`, and not CUDA 10.0 installation. That's because for example I tried to install Keras+TF and I was able to use them without any errors and train a model on GPU.

**Comment by JulianGerhard21** [comment]
Hi all, hi @honnibal @mkaze 

I faced the same issue on:

OS:
Ubuntu 18.04 LTS
Cuda 10.1 & cuddn 7.5.0
Python 3.6.8

I was able to resolve it by manually cloning ``thinc-gpu-ops``, running ``pip install -r requirements.txt`` (that actually installed cython) and then running ``pip install .``.

Actually I downgraded the library to version 0.3.0.

Hope that helps someone!

**Comment by ozancaglayan** [comment]
I think the building of thinc-gpu-ops silently fails. Initially, I did not have $CUDA_HOME set but `pip` did not give any errors at all. Then I uninstalled thinc-gpu-ops, correctly set CUDA_HOME in my environment and did a reinstall. In the first case, the `thinc-gpu-ops` had merely `.version` and internal attributes while after second install, it had all the other attributes/methods that should be there.

**Comment by rollator3000** [comment]
Hi @honnibal @ines,

after the bug from ticket #82 was solved, i encountered the same problem as mentioned here already!
**ErrorMessage:** 
`(spacy_gpu2) steve@sensopia:~/Desktop$ python train_textcat.py de_trf_bertbasecased_lg -o ./RESULTS -n 10
['sentencizer', 'trf_wordpiecer', 'trf_tok2vec']
Loaded model 'de_trf_bertbasecased_lg'
Loading IMDB data...
Labels: ('POSITIVE', 'NEGATIVE')
Positive label for evaluation: POSITIVE
Using 100 training docs, 2000 evaluation
Training the model...
LOSS 	  P  	  R  	  F  
  0%|                                                                                                                                                                               | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_textcat.py", line 282, in <module>
    plac.call(main)
  File "/home/steve/anaconda3/envs/spacy_gpu2/lib/python3.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/steve/anaconda3/envs/spacy_gpu2/lib/python3.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_textcat.py", line 128, in main
    nlp.update(texts, annotations, sgd=optimizer, drop=0.1, losses=losses)
  File "/home/steve/anaconda3/envs/spacy_gpu2/lib/python3.7/site-packages/spacy_transformers/language.py", line 108, in update
    component_cfg=component_cfg,
  File "/home/steve/anaconda3/envs/spacy_gpu2/lib/python3.7/site-packages/spacy/language.py", line 516, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "pipes.pyx", line 981, in spacy.pipeline.pipes.TextCategorizer.update
  File "/home/steve/anaconda3/envs/spacy_gpu2/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/home/steve/anaconda3/envs/spacy_gpu2/lib/python3.7/site-packages/thinc/neural/pooling.py", line 30, in begin_update
    res, bp_res = func.begin_update((X, lengths))
  File "/home/steve/anaconda3/envs/spacy_gpu2/lib/python3.7/site-packages/thinc/neural/pooling.py", line 53, in mean_pool
    output = ops.mean_pool(X, lengths)
  File "ops.pyx", line 952, in thinc.neural.ops.CupyOps.mean_pool
AttributeError: module 'thinc_gpu_ops' has no attribute 'mean_pool'`

**OS:**
Ubuntu 16.04-x86_64
CUDA 10.0
Python 3.7.4

**Enviroment**
![Enviroment](https://user-images.githubusercontent.com/23523415/67879234-e62f9b80-fb3c-11e9-8f0b-6b75c78e944b.PNG)

Thanks in Advance & keep up your great work!

**Comment by pmbaumgartner** [comment]
> Hi all, hi @honnibal @mkaze
> 
> I faced the same issue on:
> 
> OS:
> Ubuntu 18.04 LTS
> Cuda 10.1 & cuddn 7.5.0
> Python 3.6.8
> 
> I was able to resolve it by manually cloning `thinc-gpu-ops`, running `pip install -r requirements.txt` (that actually installed cython) and then running `pip install .`.
> 
> Actually I downgraded the library to version 0.3.0.
> 
> Hope that helps someone!

FYI, this worked for me and stopped the  `AttributeError: module 'thinc_gpu_ops' has no attribute 'mean_pool'` error. I'm building inside docker, so here's the `Dockerfile` that ended up working:

```
FROM pytorch/pytorch:1.2-cuda10.0-cudnn7-devel
RUN apt-get update && apt-get install -y build-essential python3-dev
WORKDIR /app
RUN pip install -U torch
RUN git clone https://github.com/explosion/thinc_gpu_ops \ 
    && cd thinc_gpu_ops \
    && pip install -r requirements.txt \
    && pip install .
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN python -m spacy download en_trf_distilbertbaseuncased_lg
COPY . .

```
There are probably some things in there that are not relevant to this problem, but I don't have time to develop a minimally repicable example right now.
