### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by SaziSuber** [explosion/spacy-pytorch-transformers#41]
`assert_almost_equal(doc.tensor.sum(axis=0), doc._.pytt_last_hidden_state.sum(axis=0), decimal=5)`

when i run this part it throws me the value error. any idea what i am doing wrong and need to fix?

```
//Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore<1.13.0,>=1.12.205->boto3->pytorch-transformers<1.1.0,>=1.0.0->spacy-pytorch-transformers) (1.12.0)
//
```

**Comment by honnibal** [comment]
I don't really see how that error could be occurring from the line you gave there. Are you sure that's correct?
