### ISSUE TITLE
RoBERTa support?

### ISSUE THREAD

**Issue by namednil** [explosion/spacy-pytorch-transformers#42]
RoBERTa is not supported yet, is it? I tried to apply the instructions [here](https://github.com/explosion/spacy-pytorch-transformers#loading-models-from-a-path) but there's no `vocab.txt` for RoBERTa but two other files (`vocab.json` and `merges.txt`).

**Comment by ines** [comment]
Will be included in the new version! 

Model here: https://github.com/explosion/spacy-models/releases/tag/en_pytt_robertabase_lg-2.1.0 –  requires `spacy-pytorch-transformers>=0.3.0`.
