### ISSUE TITLE
 a bytes-like object is required, not 'dict'

### ISSUE THREAD

**Issue by jameszlj** [explosion/spacy-pytorch-transformers#44]
env spacy=2.1.7 and spacy-pytorch-transformers==0.2.0 and en_pytt_bertbaseuncased_lg-2.1.1
import spacy
spacy.load("en_pytt_bertbaseuncased_lg-2.1.1)

reustl: a bytes-like object is required, not 'dict'
and try spacy-pytorch-transformers==0.1.0
result; the same

why????

**Comment by honnibal** [comment]
Should be fixed in the latest version, thanks.

**Comment by jameszlj** [comment]
try，but no way

发自我的 iPhone
