### ISSUE TITLE
Unexpected low similarity for similar tokens

### ISSUE THREAD

**Issue by chikubee** [explosion/spacy-pytorch-transformers#55]
@ines I was wondering if you could help me understand why there is extremely low similarity for some genuinely similar cases.
Sentence1: I am a salaried person
Sentence2: I am a person who gets salary
The similarity between the tokens salaried and salary is extremely less.
While Sentence2 actually matches with other sentences in the corpora relevant to salary, Sentence1 does not.

Does it have something to do with the word-pieces as salaried gets broken into sal ##ari ##ed?
And how exactly is the final vector constructed from wordpieces for a particular token?
<img width="866" alt="Screenshot 2019-09-04 at 11 21 04 AM" src="https://user-images.githubusercontent.com/25073753/64229832-92238480-cf08-11e9-821f-039818bf4a8a.png">

**Comment by honnibal** [comment]
There's many dimensions of "similarity". The word `"salaried"` is an adjective, so in some ways it's more similar to any other adjective than it will be to "salary".

In general it's quite hard to predict how the model will assign similarities before you train it. You might need to train it for the specific behaviours you want.

**Comment by amitjslearn** [comment]
> There's many dimensions of "similarity". The word `"salaried"` is an adjective, so in some ways it's more similar to any other adjective than it will be to "salary".
> 
> In general it's quite hard to predict how the model will assign similarities before you train it. You might need to train it for the specific behaviours you want.

@chikubee did you figure it out? @honnibal how to do fine-tuning/transfer learning for text similarity, unsupervised. Should the text be preporcessed?, if so how?
