### ISSUE TITLE
Text categorization with two sentences

### ISSUE THREAD

**Issue by fhaase2** [explosion/spacy-pytorch-transformers#57]
First of all, thank you for this awesome library!

Is it actual possible to use the pipeline with text inputs consisting of two seperate sentences, such as (e.g. question answer pairs):

`TRAIN_DATA = [
    ("text1", "text2", {"cats": {"POSITIVE": 1.0, "NEGATIVE": 0.0}})
]`

If not, it is possible to insert [CLS] and [SEP] tokens in the text input by myself and deactivate the automatic adding?

**Comment by honnibal** [comment]
@fhaase2 Yes, although it's a bit ugly at the moment. You can set the `doc._.pytt_separator` value, and use a separator token to concatenate the texts. Like this: https://github.com/explosion/spacy-pytorch-transformers/blob/master/examples/tasks/run_glue.py#L111

The `pytt_separator` value is used to calculate the `pytt_segments` extension attribute, which is then used by the wordpiecer to get the right separator tokens: https://github.com/explosion/spacy-pytorch-transformers/blob/master/spacy_pytorch_transformers/pipeline/wordpiecer.py#L77
