### ISSUE TITLE
Adding numerical metadata to textcat

### ISSUE THREAD

**Issue by tsoernes** [explosion/spacy-pytorch-transformers#60]
I have additional metadata for each text, encoded numerically, which I want to input to the last layer of the textcategorizer. My approach thus far has been to add an extension attribute to each doc:
```
Doc.set_extension('metadata', default=None)
 for doc, metadata in train_data:
      # A numpy vector
      doc._.metadata = metadata.astype(np.float32)
```
And concatting the metadata to the output layer:
```
@layerize
def get_metadata(docs, drop=0.0):
    outputs = [doc._.metadata for doc in docs]
    for out in outputs:
        assert out is not None
        assert out.size != 0

    return outputs, noop


@register_model("sigmoid_last_hidden_metadata")
def sigmoid_last_hidden_metadata(nr_class, *, exclusive_classes=False, **cfg):
    pytt_width = cfg["token_vector_width"]
    md_width = cfg["metadata_width"]
    pytt_inp = chain(
        get_pytt_last_hidden,
        flatten_add_lengths,
        Pooling(mean_pool)
    )
    metadata_inp = get_metadata
    return chain(
        concatenate(pytt_inp, metadata_inp),
        zero_init(Affine(nr_class, md_width + pytt_width, drop_factor=0.0)),
        logistic,
    )
```
Then running docs (not texts) through `nlp.update`.
However, the above approach yields errors:
```
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/spacy/language.py, line 475, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
File pipes.pyx, line 968, in spacy.pipeline.pipes.TextCategorizer.update
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py, line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/thinc/api.py, line 166, in begin_update
    shapes = [val.shape for val in values]
File /home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/thinc/api.py, line 166, in <listcomp>
    shapes = [val.shape for val in values]

AttributeError: 'list' object has no attribute 'shape'

```
Using `outputs = np.array([doc._.metadata for doc in docs])` in the `get_metadata` function does not seem to work either:
```
  Shape mismatch: input (8, 3057) not compatible with [None, 793].
```
I must have completely misunderstood spacy/thinc usage; thinc in particular is quite different from vanilla ML/numerical libraries.

**Comment by tsoernes** [comment]
Never mind. I set `metadata_width` incorrectly. Now it works fine.

**Comment by leolorenzoluis** [comment]
@tsoernes How did you register a model? And what was the solution when you mean you set metadata_width incorrectly?

**Comment by tsoernes** [comment]
@leolorenzoluis You register a model by using the decorator from `from spacy_pytorch_transformers.model_registry import register_model`. I set the meta data width with an incorrect number, not in an incorrect way.

**Comment by pbakhtin** [comment]
> @leolorenzoluis You register a model by using the decorator from `from spacy_pytorch_transformers.model_registry import register_model`. I set the meta data width with an incorrect number, not in an incorrect way.

Could you please share your zero_init and logistic definitions? I've ran into a problem #77 , your approach seems to solve it!

**Comment by tsoernes** [comment]
@pbakhtin 
```
from spacy_pytorch_transformers.model_registry import register_model
from spacy._ml import logistic
```
