### ISSUE TITLE
Differing vectors between `token.vector` and `doc._.pytt_last_hidden_state[token_id]`

### ISSUE THREAD

**Issue by dennlinger** [explosion/spacy-pytorch-transformers#68]
I was trying to figure out how the outputs from BERT/Transformers are treated afterwards and noticed that the `doc._.last_hidden_state` tensor values are different from the values encountered in the final `doc.tensor` (or `token.vector`) object.

I've verified that the assertion checks in the [intro post](https://explosion.ai/blog/spacy-pytorch-transformers) are holding true (the `assert_almost_equal()` on the sums), but I am still finding that the token-level embeddings significantly differ.

From what I can see in `tok2vec.py`, the custom hook should simply return the corresponding row in the tensor, so I don't see where the values would change. I am not sure if this is intended behavior and I just missed some further interactions, or if this is an actual bug.

Since I am not sure about the guidelines, I also want to point out that I have cross-posted the issue under the spacy tag on [Stackoverflow](https://stackoverflow.com/questions/58084661/how-are-token-vectors-calculated-in-spacy-pytorch-transformers).

**Comment by honnibal** [comment]
The `doc._.pytt_last_hidden_state` tensor has one row per wordpiece, and there might be multiple wordpieces per token. In order to avoid discarding information, we average across the multi-aligned wordpieces, weighted by the number of tokens that wordpiece is aligned to.
