### ISSUE TITLE
Is `spacy<2.2.0` required?

### ISSUE THREAD

**Issue by tamuhey** [explosion/spacy-pytorch-transformers#69]
https://github.com/explosion/spacy-pytorch-transformers/blob/ab132b674c5a91510eb8cc472cdbdf5877d24145/setup.py#L33

I want to remove `<2.2.0` part in this line to use this package with latest spacy.

**Comment by ines** [comment]
spaCy v2.2 isn't officially out yet so at the moment, this package requires v2.1. 

The spaCy version on `master` specifies its version as v2.2, so if you want to use `spacy-pytorch-transformers` with that, you should also be able to install it with `--no-deps`, to prevent it from trying to install the dependencies (or maybe you also have to set `--ignore-installed`? I always forget what the right combination of flags is). Once v2.2 is officially released, we'll definitely update this package and release a new version with `spacy>=2.1.7,<2.3.0`.

**Comment by tamuhey** [comment]
@ines Could you handle this, please
