### ISSUE TITLE
How to convert bert-base-uncased model to en_pytt_bertbaseuncased_lg by self.

### ISSUE THREAD

**Issue by IgorWang** [explosion/spacy-pytorch-transformers#78]
I want to make a chinese model from BERT-Base(Chinese) model. I don't find any document to support that. Anyone can help me?  Thanks!

**Comment by ines** [comment]
Hi! If you have the PyTorch model weights, you can follow the instructions here to create a spaCy model (`nlp` object): https://github.com/explosion/spacy-pytorch-transformers#loading-models-from-a-path

Once you have the `nlp` object, you can save it to a file using `nlp.to_disk("/path/to/model")` (and load it back using `spacy.load`). You can also use [`spacy package`](https://spacy.io/api/cli#package) to turn it into a pip-installable Python pacakge.
