### ISSUE TITLE
Typo in example 

### ISSUE THREAD

**Issue by lukemelas** [explosion/spacy-pytorch-transformers#8]
Hello authors, thank you for your work putting this together! 

I am working through the example, and I believe there is a typo [here](https://github.com/explosion/spacy-pytorch-transformers/blob/master/examples/train_textcat.py#L143).

Lines 143 and 144 are currently
```
train_texts = train_texts[-dev_size:]
train_labels = train_labels[-dev_size:]
```
But they should be:
```
train_texts = train_texts[dev_size:]
train_labels = train_labels[dev_size:]
```

Also, line 58 is
```
(train_texts, train_cats), (eval_texts, eval_cats) = load_data()
```
and it probably should be: 
```
(train_texts, train_cats), (eval_texts, eval_cats) = load_data(limit=n_texts)
```

Best,
Luke

**Comment by honnibal** [comment]
Thanks, fixed!

**Comment by lukemelas** [comment]
Great!
